// module.exports = {
//   printWidth: 100,
//   tabWidth: 2,
//   useTabs: false,
//   semi: true,
//   vueIndentScriptAndStyle: true,
//   singleQuote: true, // 单引号
//   quoteProps: 'as-needed',
//   bracketSpacing: true,
//   trailingComma: 'none',
//   arrowParens: 'always',
//   insertPragma: false,
//   requirePragma: false,
//   proseWrap: 'never',
//   htmlWhitespaceSensitivity: 'strict',
//   endOfLine: 'auto',
//   // 'eslintIntegration': true,
//   // 'stylelintIntegration': true,
//   // 'tabWidth': 2,
//   // 'printWidth': 100,
//   // 'singleQuote': true,
//   // 'semi': false,
//   // 'bracketSpacing': true,
//   // 'arrowParens': 'avoid',
//   // 'trailingComma': 'none',
//   // 'useTabs': false
// };
